# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template actions.py.jinja --
from typing import TypeVar
import warnings

from . import types, errors, bases

if TYPE_CHECKING:
    from .client import Client
    from .bases import _PrismaModel


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class PatientActions(Generic[_PrismaModelT]):
    __slots__ = (
        '_client',
        '_model',
    )

    def __init__(self, client: 'Client', model: Type[_PrismaModelT]) -> None:
        self._client = client
        self._model = model

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[_PrismaModelT]:
        """Execute a raw SQL query

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        List[prisma.models.Patient]
            The records returned by the SQL query

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        users = await Patient.prisma().query_raw(
            'SELECT * FROM Patient WHERE patient_id = ?',
            'bbadfchfja',
        )
        ```
        """
        return await self._client.query_raw(query, *args, model=self._model)

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> Optional[_PrismaModelT]:
        """Execute a raw SQL query, returning the first result

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        prisma.models.Patient
            The first record returned by the SQL query
        None
            The raw SQL query did not return any records

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        user = await Patient.prisma().query_first(
            'SELECT * FROM Patient WHERE first_name = ?',
            'dhheabfhf',
        )
        ```
        """
        return await self._client.query_first(query, *args, model=self._model)

    async def create(
        self,
        data: types.PatientCreateInput,
        include: Optional[types.PatientInclude] = None
    ) -> _PrismaModelT:
        """Create a new Patient record.

        Parameters
        ----------
        data
            Patient record data
        include
            Specifies which relations should be loaded on the returned Patient model

        Returns
        -------
        prisma.models.Patient
            The created Patient record

        Raises
        ------
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # create a Patient record from just the required fields
        patient = await Patient.prisma().create(
            data={
                # data to create a Patient record
                'first_name': 'ggciceaie',
                'last_name': 'bbehjachib',
                'age': 2035015474,
                'condition': 'dgiiaaijj',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='create',
            model=self._model,
            arguments={
                'data': data,
                'include': include,
            },
        )
        return self._model.parse_obj(resp['data']['result'])

    async def create_many(
        self,
        data: List[types.PatientCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> int:
        """Create multiple Patient records at once.

        This function is *not* available when using SQLite.

        Parameters
        ----------
        data
            List of Patient record data
        skip_duplicates
            Boolean flag for ignoring unique constraint errors

        Returns
        -------
        int
            The total number of records created

        Raises
        ------
        prisma.errors.UnsupportedDatabaseError
            Attempting to query when using SQLite
        prisma.errors.UniqueViolationError
            A unique constraint check has failed, these can be ignored with the `skip_duplicates` argument
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        total = await Patient.prisma().create_many(
            data=[
                {
                    # data to create a Patient record
                    'first_name': 'bfaiacjjfc',
                    'last_name': 'eigcfgbif',
                    'age': 1062517886,
                    'condition': 'cghideieh',
                },
                {
                    # data to create a Patient record
                    'first_name': 'biabhbdai',
                    'last_name': 'idghgaicb',
                    'age': 595337866,
                    'condition': 'hjaecfifb',
                },
            ],
            skip_duplicates=True,
        )
        ```
        """
        if self._client._active_provider == 'sqlite':
            raise errors.UnsupportedDatabaseError('sqlite', 'create_many()')

        resp = await self._client._execute(
            method='create_many',
            model=self._model,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    async def delete(
        self,
        where: types.PatientWhereUniqueInput,
        include: Optional[types.PatientInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Delete a single Patient record.

        Parameters
        ----------
        where
            Patient filter to select the record to be deleted, must be unique
        include
            Specifies which relations should be loaded on the returned Patient model

        Returns
        -------
        prisma.models.Patient
            The deleted Patient record
        None
            Could not find a record to delete

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        patient = await Patient.prisma().delete(
            where={
                'patient_id': 'cbbbjbfcii',
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='delete',
                model=self._model,
                arguments={
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return self._model.parse_obj(resp['data']['result'])

    async def find_unique(
        self,
        where: types.PatientWhereUniqueInput,
        include: Optional[types.PatientInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Find a unique Patient record.

        Parameters
        ----------
        where
            Patient filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned Patient model

        Returns
        -------
        prisma.models.Patient
            The found Patient record
        None
            No record matching the given input could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        patient = await Patient.prisma().find_unique(
            where={
                'patient_id': 'bbejhfidcb',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None
        return self._model.parse_obj(result)

    async def find_unique_or_raise(
        self,
        where: types.PatientWhereUniqueInput,
        include: Optional[types.PatientInclude] = None
    ) -> _PrismaModelT:
        """Find a unique Patient record. Raises `RecordNotFoundError` if no record is found.

        Parameters
        ----------
        where
            Patient filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned Patient model

        Returns
        -------
        prisma.models.Patient
            The found Patient record

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        patient = await Patient.prisma().find_unique_or_raise(
            where={
                'patient_id': 'bgeecijdgg',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique_or_raise',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        return self._model.parse_obj(resp['data']['result'])

    async def find_many(
        self,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.PatientWhereInput] = None,
        cursor: Optional[types.PatientWhereUniqueInput] = None,
        include: Optional[types.PatientInclude] = None,
        order: Optional[Union[types.PatientOrderByInput, List[types.PatientOrderByInput]]] = None,
        distinct: Optional[List[types.PatientScalarFieldKeys]] = None,
    ) -> List[_PrismaModelT]:
        """Find multiple Patient records.

        An empty list is returned if no records could be found.

        Parameters
        ----------
        take
            Limit the maximum number of Patient records returned
        skip
            Ignore the first N results
        where
            Patient filter to select records
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned Patient model
        order
            Order the returned Patient records by any field
        distinct
            Filter Patient records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        List[prisma.models.Patient]
            The list of all Patient records that could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the first 10 Patient records
        patients = await Patient.prisma().find_many(take=10)

        # find the first 5 Patient records ordered by the last_name field
        patients = await Patient.prisma().find_many(
            take=5,
            order={
                'last_name': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_many',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return [self._model.parse_obj(r) for r in resp['data']['result']]

    async def find_first(
        self,
        skip: Optional[int] = None,
        where: Optional[types.PatientWhereInput] = None,
        cursor: Optional[types.PatientWhereUniqueInput] = None,
        include: Optional[types.PatientInclude] = None,
        order: Optional[Union[types.PatientOrderByInput, List[types.PatientOrderByInput]]] = None,
        distinct: Optional[List[types.PatientScalarFieldKeys]] = None,
    ) -> Optional[_PrismaModelT]:
        """Find a single Patient record.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            Patient filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned Patient model
        order
            Order the returned Patient records by any field
        distinct
            Filter Patient records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.Patient
            The first Patient record found, matching the given arguments
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second Patient record ordered by the age field
        patient = await Patient.prisma().find_first(
            skip=1,
            order={
                'age': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None
        return self._model.parse_obj(result)

    async def find_first_or_raise(
        self,
        skip: Optional[int] = None,
        where: Optional[types.PatientWhereInput] = None,
        cursor: Optional[types.PatientWhereUniqueInput] = None,
        include: Optional[types.PatientInclude] = None,
        order: Optional[Union[types.PatientOrderByInput, List[types.PatientOrderByInput]]] = None,
        distinct: Optional[List[types.PatientScalarFieldKeys]] = None,
    ) -> _PrismaModelT:
        """Find a single Patient record. Raises `RecordNotFoundError` if no record was found.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            Patient filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned Patient model
        order
            Order the returned Patient records by any field
        distinct
            Filter Patient records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.Patient
            The first Patient record found, matching the given arguments

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second Patient record ordered by the condition field
        patient = await Patient.prisma().find_first_or_raise(
            skip=1,
            order={
                'condition': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first_or_raise',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return self._model.parse_obj(resp['data']['result'])

    async def update(
        self,
        data: types.PatientUpdateInput,
        where: types.PatientWhereUniqueInput,
        include: Optional[types.PatientInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Update a single Patient record.

        Parameters
        ----------
        data
            Patient record data specifying what to update
        where
            Patient filter to select the unique record to create / update
        include
            Specifies which relations should be loaded on the returned Patient model

        Returns
        -------
        prisma.models.Patient
            The updated Patient record
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        patient = await Patient.prisma().update(
            where={
                'patient_id': 'bdiicjafbj',
            },
            data={
                # data to update the Patient record to
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='update',
                model=self._model,
                arguments={
                    'data': data,
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return self._model.parse_obj(resp['data']['result'])

    async def upsert(
        self,
        where: types.PatientWhereUniqueInput,
        data: types.PatientUpsertInput,
        include: Optional[types.PatientInclude] = None,
    ) -> _PrismaModelT:
        """Updates an existing record or create a new one

        Parameters
        ----------
        where
            Patient filter to select the unique record to create / update
        data
            Data specifying what fields to set on create and update
        include
            Specifies which relations should be loaded on the returned Patient model

        Returns
        -------
        prisma.models.Patient
            The created or updated Patient record

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        patient = await Patient.prisma().upsert(
            where={
                'patient_id': 'bgehebiafc',
            },
            data={
                'create': {
                    'patient_id': 'bgehebiafc',
                    'first_name': 'biabhbdai',
                    'last_name': 'idghgaicb',
                    'age': 595337866,
                    'condition': 'hjaecfifb',
                },
                'update': {
                    'first_name': 'biabhbdai',
                    'last_name': 'idghgaicb',
                    'age': 595337866,
                    'condition': 'hjaecfifb',
                },
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='upsert',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )
        return self._model.parse_obj(resp['data']['result'])

    async def update_many(
        self,
        data: types.PatientUpdateManyMutationInput,
        where: types.PatientWhereInput,
    ) -> int:
        """Update multiple Patient records

        Parameters
        ----------
        data
            Patient data to update the selected Patient records to
        where
            Filter to select the Patient records to update

        Returns
        -------
        int
            The total number of Patient records that were updated

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # update all Patient records
        total = await Patient.prisma().update_many(
            data={
                'patient_id': 'bghffegacj'
            },
            where={}
        )
        ```
        """
        resp = await self._client._execute(
            method='update_many',
            model=self._model,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    @overload
    async def count(
        self,
        select: None = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.PatientWhereInput] = None,
        cursor: Optional[types.PatientWhereUniqueInput] = None,
    ) -> int:
        """Count the number of Patient records present in the database

        Parameters
        ----------
        select
            Select the Patient fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            Patient filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.PatientCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await Patient.prisma().count()

        # results: prisma.types.PatientCountAggregateOutput
        results = await Patient.prisma().count(
            select={
                '_all': True,
                'first_name': True,
            },
        )
        ```
        """


    @overload
    async def count(
        self,
        select: types.PatientCountAggregateInput,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.PatientWhereInput] = None,
        cursor: Optional[types.PatientWhereUniqueInput] = None,
    ) -> types.PatientCountAggregateOutput:
        ...

    async def count(
        self,
        select: Optional[types.PatientCountAggregateInput] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.PatientWhereInput] = None,
        cursor: Optional[types.PatientWhereUniqueInput] = None,
    ) -> Union[int, types.PatientCountAggregateOutput]:
        """Count the number of Patient records present in the database

        Parameters
        ----------
        select
            Select the Patient fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            Patient filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.PatientCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await Patient.prisma().count()

        # results: prisma.types.PatientCountAggregateOutput
        results = await Patient.prisma().count(
            select={
                '_all': True,
                'last_name': True,
            },
        )
        ```
        """

        # TODO: this selection building should be moved to the QueryBuilder
        #
        # note the distinction between checking for `not select` here and `select is None`
        # later is to handle the case that the given select dictionary is empty, this
        # is a limitation of our types.
        if not select:
            root_selection = ['_count { _all }']
        else:

            root_selection = [
                '_count {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))
            ]

        resp = await self._client._execute(
            method='count',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'cursor': cursor,
            },
            root_selection=root_selection,
        )

        if select is None:
            return cast(int, resp['data']['result']['_count']['_all'])
        else:
            return cast(types.PatientCountAggregateOutput, resp['data']['result']['_count'])

    async def delete_many(
        self,
        where: Optional[types.PatientWhereInput] = None
    ) -> int:
        """Delete multiple Patient records.

        Parameters
        ----------
        where
            Optional Patient filter to find the records to be deleted

        Returns
        -------
        int
            The total number of Patient records that were deleted

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # delete all Patient records
        total = await Patient.prisma().delete_many()
        ```
        """
        resp = await self._client._execute(
            method='delete_many',
            model=self._model,
            arguments={'where': where},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    # TODO: make this easier to work with safely, currently output fields are typed as
    #       not required, we should refactor the return type
    # TODO: consider returning a Dict where the keys are a Tuple of the `by` selection
    # TODO: statically type that the order argument is required when take or skip are present
    async def group_by(
        self,
        by: List['types.PatientScalarFieldKeys'],
        *,
        where: Optional['types.PatientWhereInput'] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        avg: Optional['types.PatientAvgAggregateInput'] = None,
        sum: Optional['types.PatientSumAggregateInput'] = None,
        min: Optional['types.PatientMinAggregateInput'] = None,
        max: Optional['types.PatientMaxAggregateInput'] = None,
        having: Optional['types.PatientScalarWhereWithAggregatesInput'] = None,
        count: Optional[Union[bool, 'types.PatientCountAggregateInput']] = None,
        order: Optional[Union[Mapping['types.PatientScalarFieldKeys', 'types.SortOrder'], List[Mapping['types.PatientScalarFieldKeys', 'types.SortOrder']]]] = None,
    ) -> List['types.PatientGroupByOutput']:
        """Group Patient records by one or more field values and perform aggregations
        each group such as finding the average.

        Parameters
        ----------
        by
            List of scalar Patient fields to group records by
        where
            Patient filter to select records
        take
            Limit the maximum number of Patient records returned
        skip
            Ignore the first N records
        avg
            Adds the average of all values of the specified fields to the `_avg` field
            in the returned data.
        sum
            Adds the sum of all values of the specified fields to the `_sum` field
            in the returned data.
        min
            Adds the smallest available value for the specified fields to the `_min` field
            in the returned data.
        max
            Adds the largest available value for the specified fields to the `_max` field
            in the returned data.
        count
            Adds a count of non-fields to the `_count` field in the returned data.
        having
            Allows you to filter groups by an aggregate value - for example only return
            groups having an average age less than 50.
        order
            Lets you order the returned list by any property that is also present in `by`.
            Only **one** field is allowed at a time.

        Returns
        -------
        List[prisma.types.PatientGroupByOutput]
            A list of dictionaries representing the Patient record,
            this will also have additional fields present if aggregation arguments
            are used (see the above parameters)

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # group Patient records by age values
        # and count how many records are in each group
        results = await Patient.prisma().group_by(
            ['age'],
            count=True,
        )
        ```
        """
        if order is None:
            if take is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'take\' is present')

            if skip is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'skip\' is present')

        root_selection: List[str] = [*by]
        if avg is not None:
            root_selection.append(_select_fields('_avg', avg))

        if min is not None:
            root_selection.append(_select_fields('_min', min))

        if sum is not None:
            root_selection.append(_select_fields('_sum', sum))

        if max is not None:
            root_selection.append(_select_fields('_max', max))

        if count is not None:
            if count is True:
                root_selection.append('_count { _all }')
            elif isinstance(count, dict):
                root_selection.append(_select_fields('_count', count))

        resp = await self._client._execute(
            method='group_by',
            model=self._model,
            arguments={
                'by': by,
                'take': take,
                'skip': skip,
                'where': where,
                'having': having,
                'orderBy': order,
            },
            root_selection=root_selection,
        )
        return resp['data']['result']  # type: ignore[no-any-return]



def _select_fields(root: str, select: Mapping[str, Any]) -> str:
    """Helper to build a GraphQL selection string

    This is a work around until field selection is added to the query builder.
    """

    return root + ' {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))


from . import models